# Gilda Rech

In [1]:
import torch
from torch import Tensor

# Tutorial 1b: Softmax Function

**Question:** To have the logistic regressor output probabilities, they need to be processed through a softmax layer. Implement a softmax layer yourself. What numerical issues may arise in this layer? How can you solve them? Use the testing code to confirm you implemented it correctly.

In [2]:
logits = torch.rand((1, 20)) + 100

In [3]:
def bad_softmax(x: Tensor) -> Tensor:
    return torch.exp(x) / torch.sum(torch.exp(logits), axis=0)

In [4]:
torch.sum(bad_softmax(logits))

tensor(nan)

In [5]:
def good_softmax(x: Tensor) -> Tensor:
    ###########################################################################
    # TODO: Implement a more stable way to compute softmax                    #
    ###########################################################################
    x=(x-x.max())
    return torch.exp(x) / torch.sum(torch.exp(x))

In [6]:
good_softmax(logits)*good_softmax(logits)

tensor([[0.0024, 0.0013, 0.0015, 0.0018, 0.0013, 0.0015, 0.0023, 0.0025, 0.0033,
         0.0055, 0.0053, 0.0015, 0.0023, 0.0044, 0.0012, 0.0024, 0.0049, 0.0029,
         0.0023, 0.0023]])

In [7]:
torch.sum(good_softmax(logits))

tensor(1.0000)

In [8]:
p=torch.zeros(3,3)

In [9]:
p[2, 2]=1
p

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 1.]])

Because of numerical issues like the one you just experiences, PyTorch code typically uses a `LogSoftmax` layer.

**Question [optional]:** PyTorch automatically computes the backpropagation gradient of a module for you. However, it can be instructive to derive and implement your own backward function. Try and implement the backward function for your softmax module and confirm that it is correct.

In [10]:
def derivSoft(x:Tensor) ->Tensor:
  leng=x.size()[0]
  mat=[] #torch.zeros((leng, leng))
  for i in range(leng):
    for j in range(leng):
      if i==j:
        #print(good_softmax(x[i]).shape())
        res=good_softmax(x[i].reshape(1,-1))*(1-good_softmax(x[i].reshape(1, -1)))
      else:
        res=-good_softmax(x[i])*good_softmax(x[j])
      mat.append(res)
  return mat

In [11]:
logits1 = torch.rand((2, 20)) + 100

In [12]:
derivSoft(logits1)

[tensor([[0.0374, 0.0393, 0.0486, 0.0600, 0.0444, 0.0347, 0.0591, 0.0581, 0.0690,
          0.0561, 0.0301, 0.0414, 0.0570, 0.0336, 0.0364, 0.0281, 0.0527, 0.0522,
          0.0455, 0.0633]]),
 tensor([-0.0012, -0.0015, -0.0017, -0.0022, -0.0021, -0.0013, -0.0054, -0.0023,
         -0.0025, -0.0026, -0.0022, -0.0022, -0.0038, -0.0025, -0.0014, -0.0024,
         -0.0033, -0.0021, -0.0017, -0.0051]),
 tensor([-0.0012, -0.0015, -0.0017, -0.0022, -0.0021, -0.0013, -0.0054, -0.0023,
         -0.0025, -0.0026, -0.0022, -0.0022, -0.0038, -0.0025, -0.0014, -0.0024,
         -0.0033, -0.0021, -0.0017, -0.0051]),
 tensor([[0.0310, 0.0342, 0.0316, 0.0339, 0.0430, 0.0360, 0.0778, 0.0354, 0.0329,
          0.0418, 0.0662, 0.0492, 0.0585, 0.0662, 0.0360, 0.0759, 0.0553, 0.0364,
          0.0336, 0.0689]])]

In [13]:
from torch.autograd import backward, grad

In [14]:
logitx = torch.rand((2, 20)) + 100
logitx.requires_grad=True
logitx.sum().backward()

In [15]:
logitx.grad

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.]])